WEB: ニックネーム登録画面の実装
cm-nishida-masayuki/odyssey-osaka-cx pull request #27
Opened 2024-07-10 09:41 UTC by diggymo

SSIA

2024-07-10 09:45 UTC, Shimamura-Seiya requested changes

2024-07-10 09:45 UTC, Shimamura-Seiya commented on web/src/pages/Home.tsx
> +      <RegistrationModal />
[q] 入力をし終えたら、消えるようにできますか？
このままだと、ずっと表示されっぱなしになっちゃいます。

2024-07-10 09:52 UTC, cm-iwata commented on web/src/components/RegistrationModal.tsx
> +            <input
ニックネームの桁数をMAX50桁で制限かけるようにお願いします〜
API仕様書も更新してます

https://github.com/cm-nishida-masayuki/odyssey-osaka-cx/blob/386571d3ea81a627206276c3c59e344029638791/docs/oas.yaml#L300

2024-07-11 02:56 UTC, diggymo commented on web/src/pages/Home.tsx
> +      <RegistrationModal />
@Shimamura-Seiya 
あ、そこは `RegistrationModal` のなかで制御かけてるんですけど、不味そうですか？

2024-07-11 03:00 UTC, diggymo commented on web/src/components/RegistrationModal.tsx
> +            <input
@cm-iwata 修正しました！

2024-07-11 03:07 UTC, diggymo commented on web/src/pages/Home.tsx
> +      <RegistrationModal />
具体的には、 入力を終えると`RegistrationModal `の中で

```
const [participantId, setParticipantId] =
    useLocalStore<string>("participantId");
```

の`participantId`が`null`から`string`に変化するので `return <></>;`とな理モーダルが消えるはず？です

2024-07-12 08:47 UTC, Shimamura-Seiya commented on web/src/pages/Home.tsx
> +      <RegistrationModal />
最新のコミットでちゃんと動作したのでOKです。

2024-07-12 08:48 UTC, Shimamura-Seiya approved these changes
LGTM

2024-07-12 08:53 UTC, merged